C4Context
    title Контекстная диаграмма системы
    Person(polzovatel, "Пользователь", "Пользователь системы")
    System(sistema, "Наша система", "Система, которую мы проектируем")
    System_Ext(vneshnyaya1, "Внешняя система 1", "Внешний сервис, с которым мы взаимодействуем")
    Rel(polzovatel, sistema, "Использует")
    Rel(sistema, vneshnyaya1, "Отправляет данные")