# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transaction_pb2 as transaction__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictBatch = channel.unary_unary(
                '/seminar04.v1.TransactionInference/PredictBatch',
                request_serializer=transaction__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=transaction__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.PredictBatchStream = channel.unary_stream(
                '/seminar04.v1.TransactionInference/PredictBatchStream',
                request_serializer=transaction__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=transaction__pb2.TransactionPrediction.FromString,
                _registered_method=True)
        self.AggregateTransactions = channel.stream_unary(
                '/seminar04.v1.TransactionInference/AggregateTransactions',
                request_serializer=transaction__pb2.Transaction.SerializeToString,
                response_deserializer=transaction__pb2.TransactionScoreSummary.FromString,
                _registered_method=True)
        self.PredictLive = channel.stream_stream(
                '/seminar04.v1.TransactionInference/PredictLive',
                request_serializer=transaction__pb2.Transaction.SerializeToString,
                response_deserializer=transaction__pb2.TransactionPrediction.FromString,
                _registered_method=True)


class TransactionInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatchStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateTransactions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictLive(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=transaction__pb2.PredictBatchRequest.FromString,
                    response_serializer=transaction__pb2.PredictBatchResponse.SerializeToString,
            ),
            'PredictBatchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictBatchStream,
                    request_deserializer=transaction__pb2.PredictBatchRequest.FromString,
                    response_serializer=transaction__pb2.TransactionPrediction.SerializeToString,
            ),
            'AggregateTransactions': grpc.stream_unary_rpc_method_handler(
                    servicer.AggregateTransactions,
                    request_deserializer=transaction__pb2.Transaction.FromString,
                    response_serializer=transaction__pb2.TransactionScoreSummary.SerializeToString,
            ),
            'PredictLive': grpc.stream_stream_rpc_method_handler(
                    servicer.PredictLive,
                    request_deserializer=transaction__pb2.Transaction.FromString,
                    response_serializer=transaction__pb2.TransactionPrediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seminar04.v1.TransactionInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seminar04.v1.TransactionInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seminar04.v1.TransactionInference/PredictBatch',
            transaction__pb2.PredictBatchRequest.SerializeToString,
            transaction__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/seminar04.v1.TransactionInference/PredictBatchStream',
            transaction__pb2.PredictBatchRequest.SerializeToString,
            transaction__pb2.TransactionPrediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateTransactions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/seminar04.v1.TransactionInference/AggregateTransactions',
            transaction__pb2.Transaction.SerializeToString,
            transaction__pb2.TransactionScoreSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictLive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/seminar04.v1.TransactionInference/PredictLive',
            transaction__pb2.Transaction.SerializeToString,
            transaction__pb2.TransactionPrediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
