# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0cseminar04.v1\"W\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x15\n\rinternational\x18\x03 \x01(\x08\x12\x15\n\rmerchant_risk\x18\x04 \x01(\x01\"F\n\x13PredictBatchRequest\x12/\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x19.seminar04.v1.Transaction\"K\n\x15TransactionPrediction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x12\n\nrisk_label\x18\x03 \x01(\t\"P\n\x14PredictBatchResponse\x12\x38\n\x0bpredictions\x18\x01 \x03(\x0b\x32#.seminar04.v1.TransactionPrediction\"c\n\x17TransactionScoreSummary\x12\x19\n\x11transaction_count\x18\x01 \x01(\r\x12\x14\n\x0c\x61verage_risk\x18\x02 \x01(\x01\x12\x17\n\x0fhigh_risk_count\x18\x03 \x01(\r2\xfd\x02\n\x14TransactionInference\x12U\n\x0cPredictBatch\x12!.seminar04.v1.PredictBatchRequest\x1a\".seminar04.v1.PredictBatchResponse\x12^\n\x12PredictBatchStream\x12!.seminar04.v1.PredictBatchRequest\x1a#.seminar04.v1.TransactionPrediction0\x01\x12[\n\x15\x41ggregateTransactions\x12\x19.seminar04.v1.Transaction\x1a%.seminar04.v1.TransactionScoreSummary(\x01\x12Q\n\x0bPredictLive\x12\x19.seminar04.v1.Transaction\x1a#.seminar04.v1.TransactionPrediction(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=35
  _globals['_TRANSACTION']._serialized_end=122
  _globals['_PREDICTBATCHREQUEST']._serialized_start=124
  _globals['_PREDICTBATCHREQUEST']._serialized_end=194
  _globals['_TRANSACTIONPREDICTION']._serialized_start=196
  _globals['_TRANSACTIONPREDICTION']._serialized_end=271
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=273
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=353
  _globals['_TRANSACTIONSCORESUMMARY']._serialized_start=355
  _globals['_TRANSACTIONSCORESUMMARY']._serialized_end=454
  _globals['_TRANSACTIONINFERENCE']._serialized_start=457
  _globals['_TRANSACTIONINFERENCE']._serialized_end=838
# @@protoc_insertion_point(module_scope)
